### PR TITLE
Add [[WP:NEVENT]]

### PR DESCRIPTION
**Pull request by anome2002**
Add [[WP:NEVENT]]

### CODE REVIEW

**Comment by primefac** [comment]
Just a note, we do not have an <event> decline summary in the /comments template. Should probably get that sorted before this gets merged.

**Comment by anome2002** [comment]
@primefac  , do you know where the /comments is, I can't find it so that I can update it

**Comment by primefac** [comment]
https://en.wikipedia.org/wiki/Template:AfC_submission/comments

Genuinely out of curiosity, is this something we need? I feel like it would have been discussed if there were enough <event> declines to merit a new decline reason.

**Comment by NovemLinguae** [comment]
I have modified this patch to include both book and event decline reasons. I will merge this in a day or two if there are no objections.

https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFCH_may_be_in_need_of_two_new_decline-reason_codes

**Pull request merged**
