### PR TITLE
Remove {{Draftcat}} when accepting

### PR DESCRIPTION
**Pull request by DreamRimmer**
{{Draftcat}} is a redirect to {{Draft categories}}. AFCH only detects and removes the latter when accepting a draft, but now it will also remove {{Draftcat}}.

### CODE REVIEW

**Comment by DreamRimmer** [comment]
Resolves #381

**Review by NovemLinguae — COMMENTED** [review]
Optional, but would make reviewing easier: Setting up a unit test for AFCH.Text.prototype.cleanUp = function ( isAccept ) looks like it might be easy to do here. It looks like it might just be a string in -> string out function. You could add several test cases:

* `` -> ``
* `{{Draft categories|[[Category:Test]]}}` -> `[[Category:Test]]`
* `{{draft categories|[[Category:Test]]}}` -> `[[Category:Test]]` (to test lowercase)
* `{{Draftcat|[[Category:Test]]}}` -> `[[Category:Test]]`

These tests would go in a new file called tests/test-submission.js. You could copy and adjust the code from the top of tests/test-core.js to help set everything up correctly.

**Comment by DreamRimmer** [comment]
I've tested it, and it's working fine. I tried to set up tests for submission.js, but I had some issues. I'll fix those later and upload a new file. I think this code is ready for approval.

**Comment by NovemLinguae** [comment]
> I think this code is ready for approval.

I agree :) Thanks DR!

**Pull request merged**
