### PR TITLE
handleSubmit: add "unsubmitted" as an option

### LINKED ISSUE #240: Button to add {{AfC submission|T}} to pages in draftspace that don't have it yet
Should probably add it as an option to the "Submit" dropdown, perhaps named "Unsubmitted". Would place `{{AfC submission|T}}`, which is the unsubmitted state.

image

image

### PR DESCRIPTION
**Pull request by NovemLinguae**
Fixes #240

Adds an "Unsubmitted" option to the combo box in the Submit dialog. Generates the following Wikicode: `{{AFC submission|t|ns=118|ts=}}`.

Primefac objects below, but in the bug report appears to change his mind. He brings up a good point that this should not generate a timestamp, so I have made sure my code does not generate a timestamp.

The use case is a page in the Draft namespace that does not have any AFC template at all. This lets you add the AFC submission template, but in an unsubmitted state, which is useful sometimes.

image

### CODE REVIEW

**Comment by primefac** [comment]
I do not see this as an issue that needs fixing.

**Comment by NovemLinguae** [comment]
Abandoning. Received pushback.

**Comment by NovemLinguae** [comment]
Would have been nice to have this patch today when I found this draftified draft that had no tags. Would have saved me a couple minutes looking up the template.

If folks change their mind about not liking this patch, let me know and I'll revive it.

https://en.wikipedia.org/w/index.php?title=Draft:Ibrahim_Biari&oldid=1183025066

**Comment by NovemLinguae** [comment]
Reopening due to renewed interest at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Template%3AAfC_submission%2Fdraft. Will see how that discussion shakes out then make a decision about this PR.

**Comment by Cookies52** [comment]
This ideally need to be changed to {{draft article}}, not {{afc submission}}. I also question if this should be under "Submit", maybe add a "tag as draft" to the RHS popout menu?

**Comment by NovemLinguae** [comment]
The moveToDraft script that is used for draftifications uses {{AfC submission|t}}, so that seems a bit more standard. [Example diff.](https://en.wikipedia.org/w/index.php?title=Draft:Amanda_Katrina_Morales&diff=prev&oldid=1231445570) Can you share your reasoning for preferring the {{Draft article}} tag?

What's RHS?

**Comment by Cookies52** [comment]
RHS = right hand side

My preferred reason is the fact that AFC is not mandatory for drafts, and the user should be choosing to use AfC, not forced to use it. Yes it's the preferred route, but let them decide that.
It may be the consensus is different, but I can't see the benefit to adding every draftified article straight into the AFC project if the editors don't want to use that route.

**Comment by NovemLinguae** [comment]
I'm not too worried about the rebase. Will cross that bridge after the approach and consensus are decided.

Since I'm in favor of {{AfC submission|t}} in the AFCH submit dialog, you're in favor of {{Draft article}} in some other location, and Primefac is against, we're headed towards no consensus and re-closing the patch.

**Comment by saqibq** [comment]
I'm not tech-savvy, so I'm curious why this patch isn’t being allowed?

**Comment by primefac** [comment]
Has nothing to do with the tech, but rather some folks believe that {{draft article}} should be used because "AfC is not required" and putting {{AfC submissionn/draft}} is "unduly forcing people to use the process" or somesuch.

**Comment by primefac** [comment]
No idea, but I still don't get why people don't just add {{AfC submission/draft}} since that's what the |t calls.

(as far as the t itself goes, d is for decline, a is for accept, f and r don't really make any sense so the only letter left is t? Maybe it's for "temp" or "to be submitted")

**Pull request closed without merging**
