### PR TITLE
Add comments to talk page

### PR DESCRIPTION
**Pull request by gullyn**
As requested in issue #128 -- this adds an option to the accept menu to copy the comments to the talk page. Here's what the accept menu looks like:
Screenshot from 2022-03-12 14-38-36
And here's how it looks on the talk page:
Screenshot from 2022-03-12 14-39-27

### CODE REVIEW

**Comment by NovemLinguae** [comment]
Might even want to have the comment copying check box checked by default. I know I'll be clicking it for all my accepts.

**Comment by primefac** [comment]
Absolutely not.

**Comment by gullyn** [comment]
Yeah, I agree with Primefac on this one. Almost all of my comments are "add more sources", "change x to y", "remove promotional language", etc. and it isn't necessary.

**Comment by NovemLinguae** [comment]
Seems a little counter intuitive. If the comments had occurred on the talk page originally, we wouldn't delete them once they are irrelevant. And increasing transparency is good in general. Hard to think of anywhere on Wikipedia where discussions are outright deleted.

But hey, sounds like this idea is really unpopular. So never mind!

**Comment by enterprisey** [comment]
WT:WPAFC has been asking for this one for a while so I wouldn't say the feature is that undesirable. Honestly there's an argument for merging this one. Thoughts?

**Comment by gullyn** [comment]
Yeah, this feature would be nice to have, I'm just against having the checkbox selected by default.

**Comment by enterprisey** [comment]
Gotcha, misread.

**Comment by NovemLinguae** [comment]
Sorry this has sat for 2 years.

## Consensus

The only objections I see in this PR are to having writing comments to the talk page ON by default. I don't see any objections to having writing comments be an option that is OFF by default. So I think this patch can move forward.

## Subst-ing the comment template

In the original ticket, I see a request to subst {{AfC comment}} on the talk page instead of using the template. I tried subst-ing it just now and it looks really ugly. There is a bunch of conditional logic in the subst rather than just pure formatting. For this reason, I think it's fine to leave it as the {{AfC comment}} template.

image

## Bug

During my testing just now, I did find a bug in this patch. If there are 0 {{AfC comments}} on a draft, and you tell it to write these 0 comments to the talk page, then it fails to write anything to the draft talk page, even the WikiProject AFC banner that it is supposed to.

In the interest of not having this patch sit for another 2 years, I'll try to fix that myself right now. Just a moment.

**Comment by NovemLinguae** [comment]
Bug involved checking `comments.length` when `comments` was null. Fixed.

Merging. Thanks for the patch!

**Pull request merged**
